### ISSUE TITLE
Some questions about pretrain model

### ISSUE THREAD

**Issue by skingorz** [liulu112601/PPN#2]
I see that you use a pre-trainign model in your code. How did you get your pre-train model and on which dataset did you pre-train train it.

**Comment by liulu112601** [comment]
> I see that you use a pre-trainign model in your code. How did you get your pre-train model and on which dataset did you pre-train train it.

Hi,

Thanks for your interest in our work! We don't use a pre-trained model. The torch.load() from the previous model is to keep the previous checkpoint and save time for training if it breaks. Hope this helps you.

regards,
Lu
